# Hyperparameters ------------------------------------------------------------------------------------------------------
# image HSV-Hue augmentation
hsv_h: 
  hue: 100          # Range (0-179)
  prob: 0.4         # image HSV-Hue augmentation (probability)

# image HSV-Saturation augmentation
hsv_s:
  saturation: 212   # Range (0-255)
  prob: 0.7         # image HSV-Saturation augmentation (probability)

# image HSV-Value (brightness) augmentation
hsv_v:
  brightness: 120   # Range (0-255)
  prob: 0.4         # image HSV-Value (brightness) augmentation (probability)

# Mixed image HSV augmentation (Mixed HSV-Hue, HSV-Saturation and HSV-Value (brightness))
hsv:
  hue: 2          # Range (0-179)
  saturation: 2   # Range (0-255)
  brightness: 2   # Range (0-255)
  prob: 0.4       # Mixed image HSV augmentation (probability)

# image rotation
degrees:
  deg: 10         # image rotation (+/- deg)
  prob: 0.2       # image rotation (probability)

# Random image rotation
degrees_random:
  deg: 10         # image rotation range (+deg, -deg)
  prob: 0.2       # image rotation (probability)

# (float) image translation (+/- fraction)
translate:
  translate_x: 0.2
  translate_y: 0.2
  prob: 0.1

# (float) image Random translation (+/- fraction)
translate_random:
  translate: 0.2
  prob: 0.1

# (float) image scale (+/- gain)
scale:
  scale_x: 0.2
  scale_x: 0.2
  prob: 0.5

# (float) image Random scale (+/- gain)
scale_random:
  scale: 0.2
  prob: 0.5

# (float) image shear (+/- deg)
shear:
  shear: 0.2
  prob: 0.2

# (float) Random image shear (+/- deg)
shear_random:
  shear: 0.2
  prob: 0.2

flipud: 0.0 # (float) image flip up-down (probability)
fliplr: 0.5 # (float) image flip left-right (probability)
mosaic: 1.0 # (float) image mosaic (probability)
mixup: 0.0 # (float) image mixup (probability)
copy_paste: 0.0 # (float) segment copy-paste (probability)
auto_augment: randaugment # (str) auto augmentation policy for classification (randaugment, autoaugment, augmix)
erasing: 0.4 # (float) probability of random erasing during classification training (0-1)
crop_fraction: 1.0 # (float) image crop fraction for classification evaluation/inference (0-1)